# Generated by Django 3.2 on 2021-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127, verbose_name='name')),
                ('max_registered', models.PositiveSmallIntegerField(verbose_name='max_registered')),
                ('starting_time', models.DateTimeField(verbose_name='date')),
                ('finishing_time', models.DateTimeField(verbose_name='finishing_time')),
            ],
            options={
                'verbose_name': 'Training',
            },
        ),
    ]
