# Generated by Django 3.2 on 2021-05-15 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='registered',
            field=models.ManyToManyField(blank=True, related_name='registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, related_name='waiting', to=settings.AUTH_USER_MODEL),
        ),
    ]
