# Generated by Django 3.2 on 2021-05-15 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('release_training', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Week',
            },
        ),
        migrations.AddField(
            model_name='training',
            name='trainer',
            field=models.CharField(default='-', max_length=127),
        ),
        migrations.AlterField(
            model_name='training',
            name='finishing_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='max_registered',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='training',
            name='starting_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, related_name='waiting_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.week'),
        ),
    ]
