# Generated by Django 3.2 on 2021-05-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20210515_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
