# Generated by Django 3.2 on 2021-05-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_week_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('week_number', 'year')},
        ),
    ]
