# Generated by Django 3.1.6 on 2021-07-16 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0005_alter_week_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='training',
            name='waiting_list',
        ),
        migrations.CreateModel(
            name='UserRegisterTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Reg'), ('WAITINGLIST', 'Wait')], default='WAITINGLIST', max_length=15)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'training')},
            },
        ),
    ]
