# Generated by Django 3.1.6 on 2021-07-17 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20210716_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='week',
        ),
        migrations.AddField(
            model_name='training',
            name='show_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
